---
sudo: required
services:
  - docker
language: python
python:
  - "2.6"
  - "2.7"
env:
  global:
    - OS_NAME=centos
  matrix:
    - OS_MAJOR_VERSION=6
    - OS_MAJOR_VERSION=7
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt update
  - sudo apt install -y docker-ce
  - docker --version
install:
  - wget http://archive.ubuntu.com/ubuntu/pool/universe/r/rpmlint/rpmlint_1.7-1_all.deb
  - sudo dpkg -i rpmlint_1.7-1_all.deb || sudo apt install -f -y
  - gem install mdl
  - if [[  $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install 'flake8<3.0.0'; fi
  - if [[  $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install flake8 flake8-import-order hacking; fi
script:
  # First syntax, linting and pre-test stages
  - mdl -s relaxed README.md
  - rpmlint glite-info-update-endpoints.spec
  - flake8 bin/glite-info-update-endpoints
  # Then, start the build container
  - docker run --name build_container -d -ti -v $PWD:/tmp -w /tmp $OS_NAME:$OS_MAJOR_VERSION /bin/bash -c 'while true ; do sleep 1000 ; done'
  # Now, install prerequisites for the build
  - docker exec -i -w /root build_container yum install -y rpm-build make rsync
  # Eventually build the rpm
  - docker exec -i -w /tmp build_container make rpm
  # and install it
  - docker exec -i -w /tmp/build/RPMS/noarch build_container bash -c "rpm -Uvh glite-info-update-endpoints*.el${OS_MAJOR_VERSION}.noarch.rpm"
