---
sudo: required
services:
  - docker
language: python
python:
  - "2.7"
env:
  global:
    - OS_NAME=centos
  matrix:
    - OS_MAJOR_VERSION=6
    - OS_MAJOR_VERSION=7
    - OS_MAJOR_VERSION=8
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt update
  - sudo apt install -y docker-ce
  - docker --version
install:
  - wget http://archive.ubuntu.com/ubuntu/pool/universe/r/rpmlint/rpmlint_1.7-1_all.deb
  - sudo dpkg -i rpmlint_1.7-1_all.deb || sudo apt install -f -y
  - gem install mdl
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script:
  # First syntax, linting and pre-test stages
  - mdl -s relaxed README.md
  - rpmlint glite-info-update-endpoints.spec
  - flake8 glite_info_update_endpoints/
  - pylint glite_info_update_endpoints/
  # Then, start the build container
  - docker run --name build_container -d -ti -v $PWD:/tmp -w /tmp $OS_NAME:$OS_MAJOR_VERSION /bin/bash -c 'while true ; do sleep 1000 ; done'
  # Now, install prerequisites for the build
  - docker exec -i -w /root build_container yum install -y rpm-build yum-utils
  # Eventually build the rpm
  - docker exec -i -w /tmp build_container yum-builddep -y glite-info-update-endpoints.spec
  - docker exec -i -w /tmp build_container make rpm
  # and install it
  - docker exec -i -w /tmp/build/RPMS/noarch build_container bash -c "yum localinstall -y glite-info-update-endpoints*.el${OS_MAJOR_VERSION}.noarch.rpm"
  # check binary works
  # first install CAs
  - docker exec -i build_container -c "curl http://repository.egi.eu/sw/production/cas/1/current/repo-files/EGI-trustanchors.repo > /etc/yum.repos.d/EGI-trustanchors.repo"
  - docker exec -i build_container -c "yum install -y ca-policy-egi-core"
  - docker exec -i build_container bash -c "echo 'capath = /etc/grid-security/certificates' >> /etc/glite/glite-info-update-endpoints.conf"
  - docker exec -i build_container bash -c "glite-info-update-endpoints -v -c /etc/glite/glite-info-update-endpoints.conf"
deploy:
  provider: releases
  api_key:
    secure: aa7woLamSN4Tmhg36Opm1E9FXm+aT+0smJpgjRefFzLcJ2Kc/9XjuyCvI1Sux3BgQNgQcw/ptf8Zc0+JKc3uxZETKxTELJGalK6qU6aNyZatwxEI6UFBRFb0NHMbWhfrVaapywaLoGw3DRo/FWB6LIJDuzWjQmCAUfiEFRBQhslRUcW1Z94VptHDR4+Er4KhbSm4o6Kq2QPN1Y7yFaE+Sn+ey4NpREdbHFxznXAI+E/7Vdxu9VtT/80iwGvZHeTXu6q6X7dECQ46qIhYZgTgBt9MhYF7mO5d+NjQ707ekAgKrlAWPigcX47DKwp5Rl7n4dtfFHjott+VKNKPEDqqtXAxKyBX7sKW0jDMpaQn9taWllos9Il1VwOh2lE1wifN77NsBpNyz5q6nzVmHRLHBeLpOmlYrUn0zsUla532wqXqMjOMeF/oieqQNaVct1T1Bo5zk6nZASti/wnILmgZ9C05wlp0ZZB5d9mBGMPUOgbBuNI3xz3bmsJezQlcAvoezJ6X+8lWFavkPFRy2l0mpj6eDshBfcFde1xNcselnbqReIZVAHtd48fbBO7Blx6hpOlowZYxAbwEkYn0jYTPXVByzIjKlz9gZkH927z7f+uySYawq9CllyU/q4DsNASkcY8DyiY71/TPkTBQBBjUo56xSSoVqzQhmViyDdohi/Y=
  file_glob: true
  file:
    - build/RPMS/noarch/glite-info-update-endpoints*.el${OS_MAJOR_VERSION}.noarch.rpm
    - build/SRPMS/glite-info-update-endpoints*.el${OS_MAJOR_VERSION}.src.rpm
  on:
    tags: true
