---
sudo: required
language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt update
install:
  - wget http://archive.ubuntu.com/ubuntu/pool/universe/r/rpmlint/rpmlint_1.7-1_all.deb
  - sudo dpkg -i rpmlint_1.7-1_all.deb || sudo apt install -f -y
  - gem install mdl
  - if [[  $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install 'flake8<3.0.0'; fi
  - if [[  $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install flake8 flake8-import-order hacking; fi
script:
  # syntax, linting and pre-test stages
  - mdl -s relaxed README.md
  - rpmlint glite-info-update-endpoints.spec
  - flake8 bin/glite-info-update-endpoints
