---
language: python
python:
  - "2.6"
  - "2.7"
addons:
  apt:
    packages:
      - rpmlint
install:
  - gem install mdl
  - pip install pytest flake8 flake8-import-order
script:
  # syntax, linting and pre-test stages
  - mdl -s relaxed README.md
  - rpmlint glite-info-update-endpoints.spec
  - flake8 .
  - pytest -v
