---
name: Create packages and test installation

on:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        centos-version: [7, 8, 9]
    name: Build CentOS ${{ matrix.centos-version }} RPMs
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:${{ matrix.centos-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install build requisites
        run: |
          yum install -y rpm-build yum-utils rpmlint
          yum-builddep -y glite-info-update-endpoints.spec
      - name: build rpm
        run: |
          make clean rpm
          rpmlint --file .rpmlint.ini build/RPMS/noarch/*.el${{ matrix.centos-version }}.noarch.rpm
      - name: Upload RPMs
        uses: actions/upload-artifact@v3
        with:
          name: rpms${{ matrix.centos-version }}
          path: |
            build/RPMS/noarch/glite-info-update-endpoints-*-1.el${{ matrix.centos-version }}.noarch.rpm

  install:
    strategy:
      matrix:
        centos-version: [7, 8, 9]
    name: Install CentOS ${{ matrix.centos-version }} RPMs
    needs: build
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:${{ matrix.centos-version }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rpms${{ matrix.centos-version }}
      - name: Install generated RPMs
        run: |
          yum localinstall -y glite-info-update-endpoints-*.el${{ matrix.centos-version }}.noarch.rpm
